/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.spring.boot)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Manage dependency versions using Spring Boot's BOM (applies to implementation
    // and, since testImplementation extends it, to the test classpath too).
    implementation(platform(libs.spring.boot.bom))

    // Use JUnit test framework.
    testImplementation(libs.junit)
    testImplementation(libs.spring.boot.starter.test)
    // Spring Boot 4 modularized web-MVC test support (@WebMvcTest, MockMvc) out of
    // spring-boot-starter-test and into its own starter.
    testImplementation(libs.spring.boot.starter.webmvc.test)
    // Lets the legacy JUnit 4 tests above keep running on the JUnit Platform
    // that spring-boot-starter-test pulls in (JUnit 5).
    testRuntimeOnly(libs.junit.vintage.engine)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.gson)
    implementation(libs.jeromq)
    implementation(libs.spring.boot.starter.web)

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dk.dtu.roborally.Main"
}

springBoot {
    mainClass.set("dk.dtu.roborally.BackendApplication")
}
