/*
 * This source file was generated by the Gradle 'init' task
 */
package dk.dtu.roborally;

import com.google.gson.Gson;
import dk.dtu.roborally.gateway.ZmqGateway;
import dk.dtu.roborally.objects.Game;
import dk.dtu.roborally.objects.Server;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

/**
 * Aapp of project where everything is initialized
 *
 * @author Elias
 */

public class App {

    @Getter
    private ZmqGateway zmqGateway;

    @Getter
    private final Gson gson;

    private List<Game> games = new ArrayList<>();

    public String getGreeting() {
        return "Hello World!";
    }

    public App() {

        // Make new thread for the zmq gateway such that it doesnt block the main thread
        Thread gatewayThread = new Thread() {
            public void run() {
                zmqGateway = new ZmqGateway();
                zmqGateway.init();
            }
        };
        gatewayThread.start();

        gson = new Gson();
        new Server();
    }

    public void run() {
        System.out.println(getGreeting());

        while (true) {
            // GameLoop
        }
    }
}
