/*
 * This source file was generated by the Gradle 'init' task
 */
package dk.dtu.roborally;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public App() {

    }

    public void run() {
        System.out.println(getGreeting());
    }
}
